enum Constants {
    static let login = "Login"
    static let password = "Password"
    static let guestLoginTitle = "Login as Guest"
    static let logout = "Logout"
    static let exit = "Exit"
    static let shipsListNavBarTitle = "Ships"
    static let mockImage = "placeholderImage"
    static let shipType = "Ship type: "
    static let buildYear = "Built year: "
    static let weight = "Weight in kg: "
    static let homePort = "Home port: "
    static let roles = "Roles: "
    static let tons = "tons"
    static let unknown = "Unknown"
    static let thankYou = "Thank You"
    static let thankYouMore = "Thank you for trialing this app."
    static let okButton = "OK"
    static let noInternetWarning = "No internet connection. You’re in Offline mode"
}
